//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TASKS
    {
        public int TASK_ID { get; set; }
        public int USER_ID { get; set; }
        public string TASK_SUBJECT { get; set; }
        public string TASK_DEADLINE { get; set; }
        public string TASK_NAME { get; set; }
        public int COMPLETED { get; set; }
        public string TASK_DESCRIPTION { get; set; }
    
        public virtual T_USERS T_USERS { get; set; }
    }
}
